version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mapa-glicemico-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - mapa-glicemico-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mapa_glicemico']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  mapa-glicemico-network:
    driver: bridge
